### ISSUE TITLE
I need the source code of this website, I want to deploy a similar one, I wonder if I can share it?

### ISSUE THREAD

**Issue by AndersonHJB** [andreburgaud/robotspy#176]
I need the source code of this website, I want to deploy a similar one, I wonder if I can share it?

https://pythonandturtle.com/

Email：aiyuechuang@gmail.com

**Comment by andreburgaud** [comment]
Hello @AndersonHJB ,

Thank you for reaching out! I have not released the source code for https://pythonandturtle.com/ as open-source but may consider doing so with an updated version of the site.

How urgently do you need to share this code?

Contact me directly at andre.burgaud@gmail.com to continue this discussion and to keep it separate from `robotspy`.

Thanks!

Andre

**Comment by andreburgaud** [comment]
Closing as this is not related to `robotspy` and we can continue the discussion started in this ticket via emails.
