### ISSUE TITLE
Parsing stalls due to user-agents duplication

### ISSUE THREAD

**Issue by andreburgaud** [andreburgaud/robotspy#212]
While parsing a robots.txt file like `http://22-lr.forumactif.com/robots.txt`, the parsing of the file stalls and never completes.

**Comment by andreburgaud** [comment]
@borisiskra raised this problem in issue #211 https://github.com/andreburgaud/robotspy/issues/211#issuecomment-2393730602.

**Comment by andreburgaud** [comment]
The parsing problem due to agent duplication was Fixed in Robotspy version 0.12.

**Comment by borisiskra** [comment]
Thanks, for looking at the issue.
I haven't had time to test it, as soon I can, I will

**Comment by andreburgaud** [comment]
> Thanks, for looking at the issue. I haven't had time to test it, as soon I can, I will

Thank you, @borisiskra!
